---
title: "Figure"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Definitions of some useful functions


```{r}
ker=function(x){
  return(dnorm(x))
}

ker1=function(x,h,u){
  g<-ker((x-u)/h)/h
  return(g)
}

Ker1=function(u,h){
  g<-ker(u/h)/h
  return(g)
}



dqk=function(u,X,h){
  l=length(u);
  n=length(X);
  n1=1:n;
  n2=n1-1;
  dqkf=rep(0,l)
  for(i in 1:l){
    dqkf[i]=sum(X*(Ker1(n2/n-u[i],h)-Ker1(n1/n-u[i],h)))
  }
  return(dqkf)
}

BCVfK=function(m,X,Xsd,ni,n){
  h=1/m
  qi=rep(0,n);
  qiSQ=1/(dqk(ni,X,h))^2;
  for(i in 1:n){
    qi[i]=1/dqk(ni[i],X[-i],h)
  }
  return(sum(Xsd*qiSQ)-2*mean(qi))
}

lstar<-function(x,a){
  if(x>=a) value<-log(x)
  else value<-(x/a)-1+log(a)
  return(value)
}


a_n<-function(X){
  s<-sd(X);
  n<-length(X)
  value<-(log(n)/2)^0.5/(s*n)
  return(value)
}

lsv<-function(x,a){
  lstar<-function(sx,a){
    if(sx>=a) value<-log(sx)
    else
      value<-log(a)-1+(sx/a)
    return(value)}
  return(sapply(x,lstar,a=a))}


RLCVK<-function(m,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  lsv<-Vectorize(lstar,"x")
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-dqk(u[i],y[-i],h)
  b<-mean(lsv(bc,a_n(y)))
  return(b)}

RLCVK_N<-function(m,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-dqk(u[i],y[-i],h)
  an=a_n(y)
  a=-mean(lsv(1/bc,an))
  qi=1/(dqk(u,y,h))
  qiSQ=qi^2;
  Xs<-c(0,y);
  Xsd<-Xs[2:(n+1)]-Xs[1:n]
  xs1<-Xsd*qi
  xs2<-Xsd*qiSQ
  b1<-sum(xs1[qi>=an])
  b2<-(1/(2*an))*sum(xs2[qi<an])
  value<-a+b1+b2
  return(value)}


dqkc<-function(u,X,h){
  l<-length(u);
  L=1:n;
  n<-length(X);
  dqkc<-rep(0,l);
  S<-seq(0,1,by=1/n);
  for(i in 1:l){
    Wi=pnorm((S[2:(n+1)]-u[i])/h)-pnorm((S[1:n]-u[i])/h)
    dqkc[i]<-(sum((X[2:n]-X[1:(n-1)])*Ker1(L[1:n-1]/n-u[i],h))-X[n]*Ker1(1-u[i],h)+X[1]*Ker1(-u[i],h)
              +(Ker1(1-u[i],h)-Ker1(-u[i],h))*sum(X*Wi)/sum(Wi))/sum(Wi)
  }
  return(dqkc)
}

BCVfKC=function(m,X,Xsd,ni,n){
  h=1/m
  qi=rep(0,n);
  qiSQ=1/(dqkc(ni,X,h))^2;
  for(i in 1:n){
    qi[i]=1/dqkc(ni[i],X[-i],h)
  }
  return(sum(Xsd*qiSQ)-2*mean(qi))
}

RLCVKC<-function(m,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  lsv<-Vectorize(lstar,"x")
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-dqkc(u[i],y[-i],h)
  b<-mean(lsv(bc,a_n(y)))
  return(b)}

RLCVKC_N<-function(m,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-dqkc(u[i],y[-i],h)
  an=a_n(y)
  a=-mean(lsv(1/bc,an))
  qi=1/(dqkc(u,y,h))
  qiSQ=qi^2;
  Xs<-c(0,y);
  Xsd<-Xs[2:(n+1)]-Xs[1:n]
  xs1<-Xsd*qi
  xs2<-Xsd*qiSQ
  b1<-sum(xs1[qi>=an])
  b2<-(1/(2*an))*sum(xs2[qi<an])
  value<-a+b1+b2
  return(value)}


Wn=function(a,n){
  w=rep(0,n)
  for (i in 1:n){
    w[i]=dpois(i-1,a)
  }
  return(w)
}



EQ<-function(x,y){
  Y<-sort(y);
  l<-length(x);
  n<-length(y);
  eq<-rep(0,l);
  for(i in 1:l){
    if(x[i]==1)eq[i]<-Y[n]
    else if(x[i]==0) eq[i]<-0
    else eq[i]<-Y[floor(n*x[i])+1]
  }
  return(eq)
}



dqp<-function(u,X,h){
  step<-1/h;
  l<-floor(step);
  k<-seq(0,l,by=1)
  n<-length(u);
  dqp<-rep(0,n);
  eq=EQ(k/step,X)
  for(i in 1:n){
    W=Wn(u[i]*step,l+1);
    wpp=c(-W[1],W[1:l]-W[2:(l+1)]);
    Pn=sum(W);
    wp=(wpp+W*W[l+1]/Pn)/Pn
    dqp[i]=step*sum(wp*eq)
  }
  return(dqp)
}

BCVfP=function(m,X,Xsd,ni,n){
  h=1/m
  qi=rep(0,n);
  qiSQ=1/(dqp(ni,X,h))^2;
  for(i in 1:n){
    qi[i]=1/dqp(ni[i],X[-i],h)
  }
  return(sum(Xsd*qiSQ)-2*mean(qi))
}

RLCVP<-function(m,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  lsv<-Vectorize(lstar,"x")
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-dqp(u[i],y[-i],h)
  b<-mean(lsv(bc,a_n(y)))
  return(b)}

RLCVP_N<-function(m,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-dqp(u[i],y[-i],h)
  an=a_n(y)
  a=-mean(lsv(1/bc,an))
  qi=1/(dqp(u,y,h))
  qiSQ=qi^2;
  Xs<-c(0,y);
  Xsd<-Xs[2:(n+1)]-Xs[1:n]
  xs1<-Xsd*qi
  xs2<-Xsd*qiSQ
  b1<-sum(xs1[qi>=an])
  b2<-(1/(2*an))*sum(xs2[qi<an])
  value<-a+b1+b2
  return(value)}


dqb<-function(u,X,h){
  step<-1/h;
  K<-floor(step);
  k<-seq(0,K,by=1)
  K1=K-1;
  k1=seq(0,K1,by=1)
  n<-length(u);
  dqb<-rep(0,n);
  eq=EQ(k/step,X);
  deq=eq[2:(K+1)]-eq[1:K];
  for(i in 1:n){
    B=dbinom(k1,K1,u[i]);
    dqb[i]=step*sum(B*deq)
  }
  return(dqb)
}

BCVfB=function(m,X,Xsd,ni,n){
  h=1/m
  qi=rep(0,n);
  qiSQ=1/(dqb(ni,X,h))^2;
  for(i in 1:n){
    qi[i]=1/dqb(ni[i],X[-i],h)
  }
  return(sum(Xsd*qiSQ)-2*mean(qi))
}

RLCVB<-function(m,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  lsv<-Vectorize(lstar,"x")
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-dqb(u[i],y[-i],h)
  b<-mean(lsv(bc,a_n(y)))
  return(b)}

RLCVB_N<-function(m,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-dqb(u[i],y[-i],h)
  an=a_n(y)
  a=-mean(lsv(1/bc,an))
  qi=1/(dqb(u,y,h))
  qiSQ=qi^2;
  Xs<-c(0,y);
  Xsd<-Xs[2:(n+1)]-Xs[1:n]
  xs1<-Xsd*qi
  xs2<-Xsd*qiSQ
  b1<-sum(xs1[qi>=an])
  b2<-(1/(2*an))*sum(xs2[qi<an])
  value<-a+b1+b2
  return(value)}


idqfj=function(u,X,h){
  l<-length(u);
  n<-length(X);
  dpf<-rep(0,l);
  S<-seq(0,1,by=1/n);
  Wi<-rep(0,n);
  for(i in 1:l){
    dpf[i]<-1/(mean(dnorm((X-EQ(u[i],X))/h))/h)
  }
  return(dpf)
}


BCVfJ=function(m,X,Xsd,ni,n){
  h=1/m
  qi=rep(0,n);
  qiSQ=1/(idqfj(ni,X,h))^2;
  for(i in 1:n){
    qi[i]=1/idqfj(ni[i],X[-i],h)
  }
  return(sum(Xsd*qiSQ)-2*mean(qi))
}

RLCVJ<-function(m,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  lsv<-Vectorize(lstar,"x")
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-idqfj(u[i],y[-i],h)
  b<-mean(lsv(bc,a_n(y)))
  return(b)}

RLCVJ_N<-function(m,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-idqfj(u[i],y[-i],h)
  an=a_n(y)
  a=-mean(lsv(1/bc,an))
  qi=1/(idqfj(u,y,h))
  qiSQ=qi^2;
  Xs<-c(0,y);
  Xsd<-Xs[2:(n+1)]-Xs[1:n]
  xs1<-Xsd*qi
  xs2<-Xsd*qiSQ
  b1<-sum(xs1[qi>=an])
  b2<-(1/(2*an))*sum(xs2[qi<an])
  value<-a+b1+b2
  return(value)}

idqfST=function(u,X,h,H){
  l<-length(u);
  n<-length(X);
  dpf<-rep(0,l);
  S<-seq(0,1,by=1/n);
  Wi<-rep(0,n);
  fn<-rep(0,n);
  for(i in 1:l){
    for(j in 1:n){
      Wi[j]<-integrate(ker1,lower=S[j],upper=S[j+1],u=u[i],h=H,abs.tol=0.1^100)$value
      fn[j]<-mean(dnorm((X-X[j])/h))/h
    }
    dpf[i]<-sum(Wi/fn)
  }
  return(dpf)
}

BCVfST=function(m,H,X,Xsd,ni,n){
  h=1/m
  qi=rep(0,n);
  qiSQ=1/(idqfST(ni,X,h,H))^2;
  for(i in 1:n){
    qi[i]=1/idqfST(ni[i],X[-i],h,H)
  }
  return(sum(Xsd*qiSQ)-2*mean(qi))
}

RLCVST<-function(m,H,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  lsv<-Vectorize(lstar,"x")
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-idqfST(u[i],y[-i],h,H)
  b<-mean(lsv(bc,a_n(y)))
  return(b)}




RLCVST_N<-function(m,H,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-idqfST(u[i],y[-i],h,H)
  an=a_n(y)
  a=-mean(lsv(1/bc,an))
  qi=1/(idqfST(u[i],y[-i],h,H))
  qiSQ=qi^2;
  Xs<-c(0,y);
  Xsd<-Xs[2:(n+1)]-Xs[1:n]
  xs1<-Xsd*qi
  xs2<-Xsd*qiSQ
  b1<-sum(xs1[qi>=an])
  b2<-(1/(2*an))*sum(xs2[qi<an])
  value<-a+b1+b2
  return(value)}




SPDF<-function(x,X,H,u){
  step<-1/H;
  l<-length(x);
  smf<-rep(0,l);
  M=ceiling(max(X)*step);
  k1=0:M;
  G=stepfuncS(k1/step,X);
  for(i in 1:l){
    smf[i]<-1-sum(Wn(x[i]*step,M+1)*G)-u;
  }
  return(smf)
}   

IvSPDF<-function(u,X,H){
  l<-length(u);
  smfq<-rep(0,l)
  for(i in 1:l){
    smfq[i]=uniroot(SPDF,c(0,max(X)),extendInt="upX",X=X,H=H,u=u[i])$root
  }
  return(smfq)
}


stepfuncS=function(x,y){
  n=length(x)
  u=rep(0,n)
  for (i in 1:n){
    z<-y>x[i]
    u[i]=mean(z)
  }
  return(u)
}

stepfunc=function(x,y){
  n=length(x)
  u=rep(0,n)
  for (i in 1:n){
    z<-y<=x[i]
    u[i]=mean(z)
  }
  return(u)
}

idqfp=function(u,X,h){
  step=1/h;
  l=length(u);
  M=ceiling(max(X)*step)
  k1=c(1:M)
  k2=k1-1
  l1<-floor(step);
  k<-seq(0,l1,by=1)
  G1=stepfunc(k1*h,X)
  G2=stepfunc(k2*h,X)
  w=G1-G2
  dpf=rep(0,l)
  for (i in 1:l){
    dpf[i]=sum(Wn(IvSPDF(u[i],X,h)*step,M)*w)*step
  }
  return(1/dpf)
}

BCVfIP=function(m,X,Xsd,ni,n){
  h=1/m
  qi=rep(0,n);
  qiSQ=1/(idqfp(ni,X,h))^2;
  for(i in 1:n){
    qi[i]=1/idqfp(ni[i],X[-i],h)
  }
  return(sum(Xsd*qiSQ)-2*mean(qi))
}

idqfpT=function(u,X,h,H){
  step=1/h;
  l=length(u);
  M=ceiling(max(X)*step)
  k1=c(1:M)
  k2=k1-1
  l1<-floor(step);
  k<-seq(0,l1,by=1)
  G1=stepfunc(k1*h,X)
  G2=stepfunc(k2*h,X)
  w=G1-G2
  dpf=rep(0,l)
  for (i in 1:l){
    dpf[i]=sum(Wn(IvSPDF(u[i],X,H)*step,M)*w)*step
  }
  return(1/dpf)
}




BCVfIPT=function(h,H,X,Xsd,ni,n){
  qi=rep(0,n);
  qiSQ=1/(idqfpT(ni,X,h,H))^2;
  for(i in 1:n){
    qi[i]=1/idqfpT(ni[i],X[-i],h,H)
  }
  return(sum(Xsd*qiSQ)-2*mean(qi))
}

RLCVIP<-function(m,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  lsv<-Vectorize(lstar,"x")
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-idqfp(u[i],y[-i],h)
  b<-mean(lsv(bc,a_n(y)))
  return(b)}

RLCVIP_N<-function(m,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-idqfp(u[i],y[-i],h)
  an=a_n(y)
  a=-mean(lsv(1/bc,an))
  qi=1/(idqfp(u[i],y[-i],h))
  qiSQ=qi^2;
  Xs<-c(0,y);
  Xsd<-Xs[2:(n+1)]-Xs[1:n]
  xs1<-Xsd*qi
  xs2<-Xsd*qiSQ
  b1<-sum(xs1[qi>=an])
  b2<-(1/(2*an))*sum(xs2[qi<an])
  value<-a+b1+b2
  return(value)}


RLCVIPT_N<-function(m,H,y){
  h=1/m
  n=length(y)
  y<-sort(y)
  u<-c(1:n)/n
  bc<-numeric(0)
  for(i in 1:n) bc[i]<-idqfpT(ni[i],X[-i],h,H)
  an=a_n(y)
  a=-mean(lsv(1/bc,an))
  qi=1/(idqfpT(ni[i],X[-i],h,H))
  qiSQ=qi^2;
  Xs<-c(0,y);
  Xsd<-Xs[2:(n+1)]-Xs[1:n]
  xs1<-Xsd*qi
  xs2<-Xsd*qiSQ
  b1<-sum(xs1[qi>=an])
  b2<-(1/(2*an))*sum(xs2[qi<an])
  value<-a+b1+b2
  return(value)}
```

## Data
```{r}
X=c(2.491395,  2.694097,  2.802286,  2.874669,  2.920331,  3.013239,  3.021438,  3.088601,  3.104938,  3.162394,3.335377,  3.342853,  3.382313,  3.401167,  3.495068,  3.784496,  3.808127,  3.816755,  3.823533,  3.832626, 3.921813 , 3.940625 , 3.977212 , 4.101913 , 4.103381,  4.126654,  4.164585,  4.176720,  4.179392,  4.226182, 4.248256,  4.301084,  4.304376,  4.304498 , 4.314163,  4.346515,  4.346909,  4.368364,  4.425614,  4.456237, 4.489714,  4.491997 , 4.559377,  4.643219,  4.705114,  4.713833,  4.802643,  4.819783,  4.822483,  4.879168, 4.909364,  4.911417,  4.938832,  4.941424,  5.028163 , 5.028704,  5.056515,  5.115740,  5.121600,  5.136797, 5.149034,  5.167845,  5.175567,  5.176000,  5.264432,  5.424792,  5.446244,  5.473332,  5.475013,  5.482807, 5.494250,  5.502851,  5.574171 , 5.578051,  5.748245,  5.899632,  5.977931,  5.980970,  6.095624,  6.119432, 6.215899,  6.224991,  6.229671 , 6.232130,  6.290352,  6.369806,  6.523937,  6.540567,  6.575679,  6.752975,6.820252,  6.994278,  7.050183,  7.385913,  7.516026,  7.562774,  7.621520,  7.943576,  9.678389, 10.867830)

```
## The selection of bandwidth
```{r}
X<-sort(X);
n=100;
ni=(1:n)/n;
Xs<-c(0,sort(X));
Xsd<-Xs[2:(n+1)]-Xs[1:n]

bhk=1/optimize(BCVfK, c(10, 50),X=X,Xsd=Xsd,ni=ni,n=n)$minimum
lhk_N=1/optimize(RLCVK_N, c(10, 50),y=X)$minimum

bhkc=1/optimize(BCVfKC, c(10, 50),X=X,Xsd=Xsd,ni=ni,n=n)$minimum
lhkc_N=1/optimize(RLCVKC_N, c(10, 50),y=X)$minimum

bhp=1/optimize(BCVfP, c(10, 50),X=X,Xsd=Xsd,ni=ni,n=n)$minimum
lhp_N=1/optimize(RLCVP_N, c(10, 50),y=X)$minimum

bhb=1/optimize(BCVfB, c(20, 80),X=X,Xsd=Xsd,ni=ni,n=n)$minimum
lhb_N=1/optimize(RLCVB_N, c(20, 80),y=X)$minimum

bhj=1/optimize(BCVfJ, c(1, 50),X=X,Xsd=Xsd,ni=ni,n=n)$minimum
lhj_N=1/optimize(RLCVJ_N, c(1, 50),y=X)$minimum

bhs=1/optimize(BCVfST, c(1, 50),X=X,Xsd=Xsd,ni=ni,n=n,H=0.014)$minimum
lhs_N=1/optimize(RLCVST_N, c(1, 50),y=X,H=0.014)$minimum

bhip=1/optimize(BCVfIP, c(10, 50),X=X,Xsd=Xsd,ni=ni,n=n)$minimum
lhip_N=1/optimize(RLCVIP_N, c(10, 50),y=X)$minimum

```
##  Plots
```{r}
tdqf=function(u,a,b){
  l=length(u);
  dqf=rep(0,l);
  for(i in 1:l){
    dqf[i]=1/dgamma(qgamma(u[i],a,b),a,b);
  }
  return(dqf)
} 

ylimt=c(0,25)
xlimt=c(0,2.5)
I1=0.05;
I2=0.95;
a=10
b=2




par(mfrow = c(2,2))

curve(tdqf(x,a,b),from=I1,to=I2,lty=1,xlab="u",ylab=expression("q(u)"),col=1,lwd=2.5,main=expression(q(u)),
      xlim=xlimt,ylim=ylimt)


leg.txt=c(expression(q(u)),paste("Bh-",round(bhk,4)),paste("Lh-",round(lhk_N,4)))
curve(tdqf(x,a,b),from=I1,to=I2,lty=1,xlab="u",ylab=expression("q(u)"),col=1,lwd=2.5,main=expression(hat(q)[nK](u)),
      xlim=xlimt,ylim=ylimt)
curve(dqk(x,X,bhk),add=TRUE,from=I1,to=I2,lty=1,col=2,lwd=2.5)
curve(dqk(x,X,lhk_N),add=TRUE,from=I1,to=I2,lty=2,col=9,lwd=2.5)
legend("topright", legend = leg.txt,
       lty=c(1,1,2),col=c(1,2,9),merge=TRUE)



leg.txt=c(expression(q(u)),paste("Bh-",round(bhkc,4)),paste("Lh-",round(lhkc_N,4)))
curve(tdqf(x,a,b),from=I1,to=I2,lty=1,xlab="u",ylab=expression("q(u)"),col=1,lwd=2.5,main=expression(hat(q)[nKC](u)),
      xlim=xlimt,ylim=ylimt)
curve(dqkc(x,X,bhkc),add=TRUE,from=I1,to=I2,lty=1,col=2,lwd=2.5)
curve(dqkc(x,X,lhkc_N),add=TRUE,from=I1,to=I2,lty=2,col=9,lwd=2.5)
legend("topright", legend = leg.txt,
       lty=c(1,1,2),col=c(1,2,9),merge=TRUE)


leg.txt=c(expression(q(u)),paste("Bh-",round(bhp,4)),paste("Lh-",round(lhp_N,4)))
curve(tdqf(x,a,b),from=I1,to=I2,lty=1,xlab="u",ylab=expression("q(u)"),col=1,lwd=2.5,main=expression(hat(q)[nP](u)),
      xlim=xlimt,ylim=ylimt)
curve(dqp(x,X,bhp),add=TRUE,from=I1,to=I2,lty=1,col=2,lwd=2.5)
curve(dqp(x,X,lhp_N),add=TRUE,from=I1,to=I2,lty=2,col=9,lwd=2.5)
legend("topright", legend = leg.txt,
       lty=c(1,1,2),col=c(1,2,9),merge=TRUE)
```
```{r}
par(mfrow = c(2,2))
leg.txt=c(expression(q(u)),paste("Bh-",round(bhb,4)),paste("Lh-",round(lhb_N,4)))
curve(tdqf(x,a,b),from=I1,to=I2,lty=1,xlab="u",ylab=expression("q(u)"),col=1,lwd=2.5,main=expression(hat(q)[nB](u)),
      xlim=xlimt,ylim=ylimt)
curve(dqb(x,X,bhb),add=TRUE,from=I1,to=I2,lty=1,col=2,lwd=2.5)
curve(dqb(x,X,lhb_N),add=TRUE,from=I1,to=I2,lty=2,col=9,lwd=2.5)
legend("topright", legend = leg.txt,
       lty=c(1,1,2),col=c(1,2,9),merge=TRUE)


leg.txt=c(expression(q(u)),paste("Bh-",round(bhj,4)),paste("Lh-",round(lhj_N,4)))
curve(tdqf(x,a,b),from=I1,to=I2,lty=1,xlab="u",ylab=expression("q(u)"),col=1,lwd=2.5,main=expression(hat(q)[nJ](u)),
      xlim=xlimt,ylim=ylimt)
curve(idqfj(x,X,bhj),add=TRUE,from=I1,to=I2,lty=1,col=2,lwd=2.5)
curve(idqfj(x,X,lhj_N),add=TRUE,from=I1,to=I2,lty=2,col=9,lwd=2.5)
legend("topright", legend = leg.txt,
       lty=c(1,1,2),col=c(1,2,9),merge=TRUE)



leg.txt=c(expression(q(u)),paste("Bh-",round(bhs,4)),paste("Lh-",round(lhs_N,4)))
curve(tdqf(x,a,b),from=I1,to=I2,lty=1,xlab="u",ylab=expression("q(u)"),col=1,lwd=2.5,main=expression(hat(q)[nS](u)),
      xlim=xlimt,ylim=ylimt)
curve(idqfST(x,X,bhs,H=0.05),add=TRUE,from=I1,to=I2,lty=1,col=2,lwd=2.5)
curve(idqfST(x,X,lhs_N,H=0.05),add=TRUE,from=I1,to=I2,lty=2,col=9,lwd=2.5)
legend("topright", legend = leg.txt,
       lty=c(1,1,2),col=c(1,2,9),merge=TRUE)



leg.txt=c(expression(q(u)),paste("Bh-",round(bhip,4)),paste("Lh-",round(lhip_N,4)))
curve(tdqf(x,a,b),from=I1,to=I2,lty=1,xlab="u",ylab=expression("q(u)"),col=1,lwd=2.5,main=expression(hat(q)[nIP](u)),
      xlim=xlimt,ylim=ylimt)
curve(idqfp(x,X,bhip),add=TRUE,from=I1,to=I2,lty=1,col=2,lwd=2.5)
curve(idqfp(x,X,lhip_N),add=TRUE,from=I1,to=I2,lty=2,col=9,lwd=2.5)
legend("topright", legend = leg.txt,
       lty=c(1,1,2),col=c(1,2,9),merge=TRUE)

par(mfrow=c(1,1))
```


